FROM node:16-alpine

# Dossier de travail
WORKDIR /app

# Mettre à jour npm à une version compatible
RUN npm install -g npm@8

# Ajouter node_modules/.bin au PATH
ENV PATH /app/node_modules/.bin:$PATH

# Copier uniquement les fichiers nécessaires pour installer les deps
COPY package.json package-lock.json ./

# Installer les dépendances en ignorant les peer deps cassés
RUN npm install --legacy-peer-deps

# Copier le reste de ton code
COPY . .

# Exposer le port React (si tu fais npm start)
EXPOSE 3000

# Commande par défaut
CMD ["npm", "start"]
